baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 20

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # Disqus
  disqusShortname = "oschvr-1"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 4

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "oschvr"
  site = "oschvr.com"


[languages]
  [languages.en]
    languageName = "English"
    title = "oschvr.com"
    subtitle = "a blog about software, cloud, security, money, business, travelling and life."
    owner = "oschvr"
    keywords = "software, cloud, security, money, business"
    copyright = ""
    menuMore = "social"
    readMore = "read more"
    readOtherPosts = "read other posts"
    newerPosts = "newer posts"8
    olderPosts = "older posts"
    missingContentMessage = "page not found..."
    missingBackButtonLabel = "back to home page"

    [languages.en.params.logo]
      logoText = "$ root@oschvr.com ~"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "posts"
        url = "/"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "problems"
        name = "problems"
        url = "/problems"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
        weight = 3
      [[languages.en.menu.main]]
        identifier = "snippets"
        name = "snippets"
        url = "/snippets"
        weight = 4
      [[languages.en.menu.main]]
        identifier = "uses"
        name = "uses"
        url = "/uses"
        weight = 5
      [[languages.en.menu.main]]
        identifier = "github"
        name = "github"
        pre = "<i class='fa fa-heart'></i>"
        url = "https://github.com/oschvr"
        weight = 6
      [[languages.en.menu.main]]
        identifier = "stackoverflow"
        name = "stackoverflow"
        pre = "<i class='fa fa-heart'></i>"
        url = "https://stackoverflow.com/users/3356769/oschvr"
        weight = 7
      [[languages.en.menu.main]]
        identifier = "twitter"
        name = "twitter"
        pre = "<i class='fa fa-heart'></i>"
        url = "https://twitter.com/oschvr"
        weight = 8
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "linkedin"
        pre = "<i class='fa fa-heart'></i>"
        url = "https://www.linkedin.com/in/oscarchavezromero/"
        weight = 9